# -*- coding: utf-8 -*-
"""Car-OOP-Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYPOF6cluJ76IB3Q_TLqDWDjXIjwLlh6

# Task1: Create a class Car with attributes brand, model, and year. Instantiate an object and print its details.
"""

class car:
  def __init__(self,brand,model,year):
    self.brand=brand
    self.model=model
    self.year=year



  def display_info(self):
    print(f"car details : \n brand:{self.brand} \n model:{self.model} \n year:{self.year}")

my_car= car(" Chevrolet","Camaro" ,2024)
my_car.brand="bmw"
my_car.display_info()

print(my_car.brand)

"""# Task2: Add a method start_engine to the Car class that prints "The engine is starting."
"""

class car:
  def __init__(self,brand,model,year,speed):
    self.brand=brand
    self.model=model
    self.year=year
    self.speed=speed


  def display_info(self):
    print(f"car details : \n brand:{self.brand} \n model:{self.model} \n year:{self.year}")


  #def start_engine(self):
   # print("The engine is starting")


  def start_engine(self):
    if self.speed >=0:
      print("The engine is starting")
    else:
      print("The engine is already running")



my_car= car(" Chevrolet","Camaro" ,2024,120)
my_car.display_info()
my_car.start_engine()

"""# Task3: Add private attributes _speed to the Car class and provide get_speed and set_speed methods to access them."""

class car:
  def __init__(self,brand,model,year,speed):
    self.brand=brand
    self.model=model
    self.year=year
    self.__speed=speed


  def display_info(self):
    print(f"car details : \n brand:{self.brand} \n model:{self.model} \n year:{self.year}")




  def get_speed(self):
    return self.__speed



  def set_speed(self,speed):
    if self.__speed <0:
      print("speed cannot be negative!")
    else:
      self.__speed=speed
      print(f"speed set to {self.__speed}")


my_car= car(" Chevrolet","Camaro" ,2024,120)
my_car.display_info()
my_car.set_speed(60)
my_car.get_speed()

"""# Task4: Create a class ElectricCar that inherits from Car and adds an additional attribute battery_capacity."""

class car:
  def __init__(self,brand,model,year):
    self.brand=brand
    self.model=model
    self.year=year



  def display_info(self):
    return f"car details : \n brand:{self.brand} \n model:{self.model} \n year:{self.year}"

my_car= car(" Chevrolet","Camaro" ,2024)
my_car.display_info()

class ElectricCar(car):
  def __init__(self,brand,model,year,battery_capacity):
    super().__init__(brand,model,year)
    self.battery_capacity=battery_capacity

  def display_info(self):
    car_info =super().display_info()
    return f"{car_info} \n battery capacity: {self.battery_capacity}"


#ecar=ElectricCar(brand="Tesla",model="Model S",year=2023,battery_capacity=75)
ecar=ElectricCar("Tesla","Model S",2023,75)
ecar.display_info()

#another solution




class ElectricCar(car):
  def __init__(self,brand,model,year,battery_capacity):
    super().__init__(brand,model,year)
    self.battery_capacity=battery_capacity

  def display_info(self):
    super().display_info()
    print(f"battery capacity: {self.battery_capacity}")


ecar=ElectricCar("Tesla","Model S",2023,75)
ecar.display_info()

"""# Task5: Add a method fuel_type to both Car and ElectricCar classes. For Car, it should return "Petrol/Diesel" and for ElectricCar, it should return "Electricity."
"""

class car:
  def __init__(self,brand,model,year,speed):
    self.brand=brand
    self.model=model
    self.year=year
    self.__speed=speed


  def display_info(self):
    print(f"car details : \n brand:{self.brand} \n model:{self.model} \n year:{self.year}")

  def get_speed(self):
    return self.__speed

  def set_speed(self,speed):
    if self.__speed <0:
      print("speed cannot be negative!")
    else:
      self.__speed=speed
      print(f"speed set to {self.__speed}")


  def fuel_type(self):
    return "petrol/diesel"




class ElectricCar(car):
  def __init__(self,brand,model,year,battery_capacity):
    super().__init__(brand, model, year, speed=0)
    self.battery_capacity=battery_capacity

  def display_info(self):
    super().display_info()
    print(f"battery capacity: {self.battery_capacity}")

  def fuel_type(self):
    return "Electricity"


f=car(" Chevrolet","Camaro" ,2024,120)
f.display_info()
print(f.fuel_type())


# their is a proplem down here
e=ElectricCar("Tesla","Model S",2023,75)
e.display_info()
print(e.fuel_type())

"""# Task6: Add a static method is_motor_vehicle to the Car class that returns True."""

class car:
  def __init__(self,brand,model,year):
    self.brand=brand
    self.model=model
    self.year=year



  def display_info(self):
    print(f"car details : \n brand:{self.brand} \n model:{self.model} \n year:{self.year}")



 #مشفاهم ال @STATIC METHOD
  @staticmethod
  def is_motor_vehicle():
    return True


my_car= car(" Chevrolet","Camaro" ,2024)
my_car.display_info()
print(car.is_motor_vehicle())

"""# Task7: Override the start_engine method in ElectricCar to include "The electric engine is silent."
"""

class car:
  def __init__(self,brand,model,year,speed):
    self.brand=brand
    self.model=model
    self.year=year
    self.speed=speed


  def display_info(self):
    print(f"car details : \n brand:{self.brand} \n model:{self.model} \n year:{self.year}")


  #def start_engine(self):
   # print("The engine is starting")


  def start_engine(self):
    if self.speed >=0:
      print("The engine is starting")
    else:
      print("The engine is already running")




class ElectricCar(car):
    def start_engine(self):
      super().start_engine()
      print("The electric engine is silent.")



my_electric = ElectricCar("Tesla", "Model S", 2023, 0)
my_electric.display_info()
my_electric.start_engine()

"""# Task8: Create a custom exception BatteryLowError and raise it in the ElectricCar class if the battery is below a certain threshold."""

class car:
    def __init__(self, brand, model, year, speed):
        self.brand = brand
        self.model = model
        self.year = year
        self.speed = speed

    def display_info(self):
        print(f"car details:\n brand: {self.brand} \n model: {self.model} \n year: {self.year}")

    def fuel_type(self):
        return "Gasoline"


class ElectricCar(car):
    def __init__(self, brand, model, year, speed, battery_capacity):
        super().__init__(brand, model, year, speed)
        self.battery_capacity = battery_capacity

    def display_info(self):
        car_info = super().display_info()
        print(f"battery capacity: {self.battery_capacity}%")

    def fuel_type(self):
        return "Electricity"


    def check_battery(self):
        if self.battery_capacity <= 10:
            raise ValueError("Battery is too low to operate.")
        else:
            print("✅ Battery is OK.")



try:
    my_electric = ElectricCar("Tesla", "Model S", 2023, 0, 8)
    my_electric.display_info()
    my_electric.check_battery()
except ValueError as e:
    print("⚠️ Error:", e)